on:
  push:
    branches:
      - main
      - development
  pull_request:

name: tidy-code

jobs:
  tidyCode:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.4.1
          use-public-rspm: true

      - name: Cache renv packages
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ubuntu-latest-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ubuntu-latest-renv-
        
      - name: Restore renv snapshot
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      
      - name: Tidy code
        shell: Rscript {0}
        run: |
            source("global.R")
        
            codeChecks <- tidy_code()
            
            if(any(is.na(codeChecks))) {
              stop("There is a breaking error in the code.")
            } else {
              if(TRUE %in% codeChecks) {
                stop("The code is not styled correctly. Open the project in RStudio and use tidy_code() to restyle the code.")
              } else {
                message("----------------------------------------")
                message("The code is beautiful, go you!")
                message("----------------------------------------")
              }
            }

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-tests
          path: tests
